services:
  sportfar-backend:
    build: .
    container_name: sportfar-backend
    environment:
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${BACKEND_PORT}
    ports:
      - "3000:3000"
