services:
  mysql:
    image: mysql:9.3
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - "db:/var/lib/mysql"

  sportfar-backend:
    build: .
    container_name: sportfar-backend
    depends_on:
      - mysql
    environment:
      DB_PORT: ${DB_PORT}
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${BACKEND_PORT}
    ports:
      - "5000:${BACKEND_PORT}"
    command: "npm run helper:migrate_and_run"

volumes:
  db:
